### ISSUE TITLE
Opam package compiling with Coq 8.10

### ISSUE THREAD

**Issue by herbelin** [coq-community/bertrand#5]
Hi @Zimmi48: I updated "bertrand" to 8.9 and 8.10 and pushed corresponding tags v8.9.0 and v8.10.0.

I did not create/update an opam package for compilation with 8.9 and 8.10. There is an opam template in the archive which I could use, but I lost track of whom is supposed to be in charge of it (the opam file says it is @palmskog but the header of the repository says it is @herbelin).

**Comment by Zimmi48** [comment]
@palmskog has just been put as a default maintainer in the opam files by the template generation process. You can override this and put yourself by setting the `opam-file-maintainer` variable in the `meta.yml` file. In any case, feel free to publish the new versions on opam of this package (of which you are indeed the maintainer) and of any other package in fact (the good thing about the publishing process being via a git repository is that it is easy to collaborate on publishing packages, and it doesn't need to be always the maintainer who does it). I am not sure what difference it makes to copy the opam file from here or from the previous versions in the opam archive.
